project:
  type: website
  render: # DO NOT RENDER OLD .Rmd files!
    - "*.qmd"
    - "*.markdown"
    - "!R/"

website:
  title: "Simon Coulombe"
  site-url: https://simonssnippets.netlify.app/
  repo-url: https://github.com/simoncoulombe/snippets_quarto
  favicon: images/favicon.ico
  description: "apprendre des trucs en public dans l'espoir de les oublier moins rapidement."
  navbar:
#    title: false   # on en a juste besoin dans l'index, pis c'est déjà le titre de l'index.qmd, pas besoin de l'avoir en haut aussi..
#    logo: images/pelleteux_carre.jpg
    left:
      - text: "Les Pelleteux de cloud"
        file: pelleteux.qmd            
      - text: "Blog"
        file: blog.qmd
      - text: "Shiny"
        file: shiny.qmd        

    right:        
      - icon: twitter
        href: https://twitter.com/coulsim
      - icon: linkedin
        href: https://www.linkedin.com/in/simon-c-310547112/
      - icon: github
        href: https://github.com/simoncoulombe
      - icon: envelope   
        href: mailto:janedoe@amazing.net    
      - icon: rss
        href: blog.xml        # https://quarto.org/docs/websites/website-blog.html
  google-analytics:  
    tracking-id: "UA-112244835-1" 
    anonymize-ip: true
    storage: "none" # no tracking of user between sesision # https://quarto.org/docs/websites/website-tools.html#google-analytics
  cookie-consent: false # dont request cookie consent  https://quarto.org/docs/websites/website-tools.html#cookie-consent
  reader-mode: true # allow users to hide side nav and table of content
  open-graph: true # richer sharing of links to articles on the web (better preview of links pasted on linkedin etc..)
lang: fr    
language: 
  title-block-author-single: "Auteur" #  i know my gender..https://github.com/quarto-dev/quarto-cli/discussions/2796#discussioncomment-3851669
format:
  html:
    theme: cerulean
    css: styles.css
    code-overflow: wrap
    code-fold: true
    code-folding: hide
    code-summary: "\\<code\\>"
    code-copy: hover
    email-obfuscation: javascript
editor: source
execute:
  freeze: auto
comments:
  giscus:
    repo: "simoncoulombe/snippets_quarto"
    repo-id: "R_kgDOLvcBAw"
    category: "Blog posts"
    category-id: "DIC_kwDOLvcBA84CewTE"
    mapping: "pathname"
    reactions-enabled: true
    input-position: "top"
    theme: "preferred_color_scheme"
    language: "fr"
    loading: "lazy"


