---
title: "Références"
comments: false  
about:
  template: jolla
  links:  # see https://icons.getbootstrap.com/ for icons
    - icon: twitter
      text: Twitter
      href: https://twitter.com/coulsim
    - icon: linkedin
      text: LinkedIn
      href: https://www.linkedin.com/in/simon-c-310547112/
    - icon: github
      text: Github
      href: https://github.com/simoncoulombe
    - icon: envelope   
      text: Email
      href: mailto:janedoe@amazing.net
---

Yo,

Je radote souvent sur des produits ou des compagnies qui me plaisent, alors tant qu'à faire je partage des codes de références qui peuvent nous donner à tous les deux un petits montant.

**Langues**

italki.com - - [lien à cliquer](https://www.italki.com/en/i/ref/AeEf0Ea?hl=en) Here's \$5 to help kickstart your journey. After registering, enter "Me Center", select "redeem", and enter the referral code **AeEf0Ea** within 24 hours. Apparemment ça me donne 10\$ une fois que vous aurez acheté pour 20\$USD

preply.com -- [lien à cliquer pour 70% de rabais sur votre trial lesson. moi ça me donne apparemment 70\$](https://preply.com/en/?pref=Mjg0MDgwMTc=&id=1785950050.83329&ep=)

**telecomm**

Fizz.ca - code de référence **9D78A**

**sites d'investissements**

**webull.ca**  - honnêtement c'est une interface de marde digne de temu avec des gros popups, mais l'automne dernier ils m'ont donné 2% de la valeur des placements unregistered que j'ai transféré chez eux alors ça valait quand même la peine. Voici [mon lien de référencement](https://www.webull.ca/s/lBUcaRDke2HTFvbQXJ), je ne sais pas quelle est la promo au moment de lire ces lignes ni ce que ça me donne présentement.

**questrade.com -** c'est un peu meilleur comme interface, au moment d'écrire ces lignes ça nous donne 50\$ à tous les deux si vous ouvrez un compte avec mon [lien de référencement questrade](https://start.questrade.com/?oaa_promo=395724586396825&s_cid=RAF14_share_link_refer_a_friend_email&utm_medium=share_link&utm_source=refer_a_friend&utm_campaign=RAF14&utm_content=personalized_link).

**wealthsimple**  - **to do.** c'est probablement là que mes placements vont finir une fois que j'aurai épuisé les bonus de transferts de la compétition :)
